version: '3.8'

services:
  rex-api-gateway:
    build: .
    container_name: rex-api-gateway
    ports:
      - "9000:9000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - rex_shared_network
    depends_on:
      mysql_server:
        condition: service_healthy
      redis_server:
        condition: service_started

  mysql_server:
    image: mysql:8.0
    container_name: rex-mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s
    networks:
      - rex_shared_network

  redis_server:
    image: redis:alpine
    container_name: rex-redis-server
    restart: always
    ports:
      - "6379:6379"
    networks:
      - rex_shared_network

networks:
  rex_shared_network:
    name: rex_shared_network
    driver: bridge

volumes:
  mysql_data: